# Generated by Django 5.0.6 on 2024-06-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anwedding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banquetroom',
            name='area',
        ),
        migrations.RemoveField(
            model_name='banquetroom',
            name='kind_of_table',
        ),
        migrations.RemoveField(
            model_name='banquetroom',
            name='room_shape',
        ),
        migrations.RemoveField(
            model_name='banquetroom',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='banquetroom',
            name='table',
        ),
    ]
