# Generated by Django 5.0.6 on 2024-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anwedding', '0002_remove_banquetroom_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='wedding_service',
        ),
        migrations.AddField(
            model_name='feedback',
            name='wedding_service',
            field=models.ManyToManyField(to='anwedding.weddingservice'),
        ),
    ]
